version: '3'
services:
  server:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mynetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  client:
    build:
      context: redis-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - mynetwork
  redis:
    image: redis
    networks:
      - mynetwork

networks:
  mynetwork: